name = "email-worker"
main = "src/worker.ts"
compatibility_date = "2024-09-25"
workers_dev = true

send_email = [
    {type = "send_email", name = "SEB"},
]

[vars]
ALLOWED_ORIGINS = "*"
RECIPIENT_ADDRESS = "*"
SENDER_ADDRESS = "*"
SENDER_NAME = "*"
